language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
install:
    - npm install
    - lerna link
before_script:
    - npm run build
branches:
    only:
        - master
